// type RoomAgentPlayerMonitor struct {
// 	ServerID   int    `json:"roomID"`
// 	RoomName   string `json:"roomName"`
// 	Agent      int    `json:"agent"`
// 	PlayerName string `json:"playerName"`
// 	//今日盈利率
// 	PlayerProfitRate struct {
// 		Value          float64  `json:"value"`
// 		YesterdayRatio *float64 `json:"yesterdayRatio"`
// 	} `json:"playerProfitRate"`
// 	//今日盈利
// 	PlayerProfit struct {
// 		Value          int      `json:"value"`
// 		YesterdayRatio *float64 `json:"yesterdayRatio"`
// 	} `json:"playerProfit"`
// 	//今日投注
// 	PlayerCellScore struct {
// 		Value          int      `json:"value"`
// 		YesterdayRatio *float64 `json:"yesterdayRatio"`
// 	} `json:"playerCellScore"`
// 	//今日局数
// 	PlayerGameNum struct {
// 		Value          int      `json:"value"`
// 		YesterdayRatio *float64 `json:"yesterdayRatio"`
// 	} `json:"playerGameNum"`
// 	//总盈利率
// 	PlayerTotalProfitRate struct {
// 		Value          float64  `json:"value"`
// 		YesterdayRatio *float64 `json:"yesterdayRatio"`
// 	} `json:"playerTotalProfitRate"`
// 	//总局数
// 	PlayerTotalGameNum struct {
// 		Value          int      `json:"value"`
// 		YesterdayRatio *float64 `json:"yesterdayRatio"`
// 	} `json:"playerTotalGameNum"`
// 	//注册时间/注册天数
// 	PlayerRegisterTime string `json:"playerRegisterTime"`

// 	//今日房间盈利
// 	RoomPlayerProfit struct {
// 		Value          int      `json:"value"`
// 		YesterdayRatio *float64 `json:"yesterdayRatio"`
// 	} `json:"roomPlayerProfit"`

// 	//今日房间投注
// 	RoomPlayerCellScore struct {
// 		Value          int      `json:"value"`
// 		YesterdayRatio *float64 `json:"yesterdayRatio"`
// 	} `json:"roomPlayerCellScore"`
// 	//今日房间局数
// 	RoomPlayerGameNum struct {
// 		Value          int      `json:"value"`
// 		YesterdayRatio *float64 `json:"yesterdayRatio"`
// 	} `json:"roomPlayerGameNum"`
// }

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: proto/APIRoomAgentPlayerMonitorResponse.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type APIRoomAgentPlayerMonitorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *APIRoomAgentPlayerMonitorResponse) Reset() {
	*x = APIRoomAgentPlayerMonitorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_APIRoomAgentPlayerMonitorResponse_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *APIRoomAgentPlayerMonitorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*APIRoomAgentPlayerMonitorResponse) ProtoMessage() {}

func (x *APIRoomAgentPlayerMonitorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_APIRoomAgentPlayerMonitorResponse_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use APIRoomAgentPlayerMonitorResponse.ProtoReflect.Descriptor instead.
func (*APIRoomAgentPlayerMonitorResponse) Descriptor() ([]byte, []int) {
	return file_proto_APIRoomAgentPlayerMonitorResponse_proto_rawDescGZIP(), []int{0}
}

var File_proto_APIRoomAgentPlayerMonitorResponse_proto protoreflect.FileDescriptor

var file_proto_APIRoomAgentPlayerMonitorResponse_proto_rawDesc = []byte{
	0x0a, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x41, 0x50, 0x49, 0x52, 0x6f, 0x6f, 0x6d, 0x41,
	0x67, 0x65, 0x6e, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4d, 0x6f, 0x6e, 0x69, 0x74, 0x6f,
	0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x05, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x23, 0x0a, 0x21, 0x41, 0x50, 0x49, 0x52, 0x6f, 0x6f,
	0x6d, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4d, 0x6f, 0x6e, 0x69,
	0x74, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x09, 0x5a, 0x07, 0x2e,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_APIRoomAgentPlayerMonitorResponse_proto_rawDescOnce sync.Once
	file_proto_APIRoomAgentPlayerMonitorResponse_proto_rawDescData = file_proto_APIRoomAgentPlayerMonitorResponse_proto_rawDesc
)

func file_proto_APIRoomAgentPlayerMonitorResponse_proto_rawDescGZIP() []byte {
	file_proto_APIRoomAgentPlayerMonitorResponse_proto_rawDescOnce.Do(func() {
		file_proto_APIRoomAgentPlayerMonitorResponse_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_APIRoomAgentPlayerMonitorResponse_proto_rawDescData)
	})
	return file_proto_APIRoomAgentPlayerMonitorResponse_proto_rawDescData
}

var file_proto_APIRoomAgentPlayerMonitorResponse_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_proto_APIRoomAgentPlayerMonitorResponse_proto_goTypes = []interface{}{
	(*APIRoomAgentPlayerMonitorResponse)(nil), // 0: proto.APIRoomAgentPlayerMonitorResponse
}
var file_proto_APIRoomAgentPlayerMonitorResponse_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_APIRoomAgentPlayerMonitorResponse_proto_init() }
func file_proto_APIRoomAgentPlayerMonitorResponse_proto_init() {
	if File_proto_APIRoomAgentPlayerMonitorResponse_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_APIRoomAgentPlayerMonitorResponse_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*APIRoomAgentPlayerMonitorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_APIRoomAgentPlayerMonitorResponse_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_APIRoomAgentPlayerMonitorResponse_proto_goTypes,
		DependencyIndexes: file_proto_APIRoomAgentPlayerMonitorResponse_proto_depIdxs,
		MessageInfos:      file_proto_APIRoomAgentPlayerMonitorResponse_proto_msgTypes,
	}.Build()
	File_proto_APIRoomAgentPlayerMonitorResponse_proto = out.File
	file_proto_APIRoomAgentPlayerMonitorResponse_proto_rawDesc = nil
	file_proto_APIRoomAgentPlayerMonitorResponse_proto_goTypes = nil
	file_proto_APIRoomAgentPlayerMonitorResponse_proto_depIdxs = nil
}
